import type { JiraQueryDef } from "./types";

export const JIRA_QUERIES: JiraQueryDef[] = [
  {
    id: "throughput",
    sheet: "1_Throughput_WorkType",
    label: "Throughput + Work Type Distribution + Planned vs Unplanned",
    metrics: "Throughput, Work Type Distribution, Planned vs. Unplanned",
    jql: 'project IN (LSCI, LVAIRD) AND status = Done AND resolved >= -26w ORDER BY resolved DESC',
  },
  {
    id: "velocity",
    sheet: "2_Velocity",
    label: "Velocity + Velocity Stability",
    metrics: "Velocity, Velocity Stability",
    jql: 'project IN (LSCI, LVAIRD) AND status = Done AND resolved >= -26w AND "Story Points" > 0 ORDER BY resolved DESC',
  },
  {
    id: "cycle_time",
    sheet: "3_CycleTime",
    label: "Cycle Time",
    metrics: "Cycle Time",
    jql: 'project IN (LSCI, LVAIRD) AND status = Done AND resolved >= -26w AND status WAS "In Progress" ORDER BY resolved DESC',
  },
  {
    id: "wip",
    sheet: "4_WIP",
    label: "Work in Progress (current snapshot)",
    metrics: "Work in Progress",
    jql: 'project IN (LSCI, LVAIRD) AND status = "In Progress" ORDER BY priority DESC',
  },
  {
    id: "backlog_readiness",
    sheet: "5_BacklogReadiness",
    label: "Backlog Readiness",
    metrics: "Backlog Readiness",
    jql: 'project IN (LSCI, LVAIRD) AND status = "Ready for Development" AND sprint is EMPTY ORDER BY priority DESC',
  },
  {
    id: "all_bugs",
    sheet: "6_AllBugs",
    label: "All Bugs (Defect Count / Defect Density)",
    metrics: "Defect Count, Defect Density",
    jql: "project IN (LSCI, LVAIRD) AND issuetype = Bug AND created >= -26w ORDER BY created DESC",
  },
  {
    id: "prod_bugs",
    sheet: "7_ProdBugs",
    label: "Production Bugs (Defect Escape Rate)",
    metrics: "Defect Escape Rate",
    jql: 'project IN (LSCI, LVAIRD) AND issuetype = Bug AND created >= -26w AND labels = "prod-bug" ORDER BY created DESC',
  },
  {
    id: "regressions",
    sheet: "8_Regressions",
    label: "Regression Bugs",
    metrics: "Regression Rate",
    jql: 'project IN (LSCI, LVAIRD) AND issuetype = Bug AND labels = "regression" AND created >= -26w ORDER BY created DESC',
  },
  {
    id: "rework",
    sheet: "9_Rework",
    label: "Rework (reopened issues)",
    metrics: "Rework Rate",
    jql: "project IN (LSCI, LVAIRD) AND status WAS Done AND status != Done AND updated >= -26w ORDER BY updated DESC",
  },
  {
    id: "unplanned_work",
    sheet: "10_UnplannedWork",
    label: "Unplanned Work (Bugs + Incidents completed)",
    metrics: "Planned vs. Unplanned (unplanned side)",
    jql: "project IN (LSCI, LVAIRD) AND issuetype IN (Bug, Incident) AND status = Done AND resolved >= -26w ORDER BY resolved DESC",
  },
  {
    id: "discovery",
    sheet: "11_Discovery",
    label: "Discovery / Investigation Work",
    metrics: "Discovery & Investigation Ratio",
    jql: 'project IN (LSCI, LVAIRD) AND labels IN ("spike", "research", "investigation") AND status = Done AND resolved >= -26w ORDER BY resolved DESC',
  },
  {
    id: "blocked",
    sheet: "12_Blocked",
    label: "Blocked Issues (Dependencies)",
    metrics: "Cross-Team Dependencies",
    jql: 'project IN (LSCI, LVAIRD) AND status WAS "Blocked" DURING (startOfMonth(-6), now()) ORDER BY updated DESC',
  },
  {
    id: "aging_backlog",
    sheet: "13_AgingBacklog",
    label: "Aging Backlog (no update in 30+ days)",
    metrics: "Aging Backlog",
    jql: "project IN (LSCI, LVAIRD) AND status NOT IN (Done, Closed, Cancelled) AND updated <= -30d ORDER BY updated ASC",
  },
];

export const JIRA_COLUMNS = [
  "Query",
  "Project",
  "Key",
  "Summary",
  "Issue Type",
  "Status",
  "Priority",
  "Assignee",
  "Reporter",
  "Sprint",
  "Story Points",
  "Labels",
  "Components",
  "Fix Versions",
  "Created",
  "Updated",
  "Resolved",
  "Resolution",
  "Time Estimate (hrs)",
  "Time Spent (hrs)",
  "Epic",
];
